@SecureHardwareLogisticsAPI_HostAddress = http://localhost:5047/v1/api

GET {{SecureHardwareLogisticsAPI_HostAddress}}/assets/
Accept: application/json

###
PUT {{SecureHardwareLogisticsAPI_HostAddress}}/assets/:id
Accept: application/json

###